### ISSUE TITLE
ControlType.multiselect doesn't seem to work

### ISSUE THREAD

**Issue by ljilekor** [idling-mind/flowfunc#16]
Problems setting ControlType.multiselect

just changed **_type = ControlType.multiselect_** in the code from[ Upload files in nodes #13 ](https://github.com/idling-mind/flowfunc/issues/13)

`
def file_selector(infile):
    return infile

file_selector_control = Control(
    type= **_ControlType.multiselect_**,
    name="file_selector",
    label="Select a File",
    options=[
        # List your files in here. Create this dictionary from the uploaded files.
        {"value": "file1.txt", "label": "this is file 1"},
        {"value": "file2.txt", "label": "this is file 2"},
    ],
)
file_selector_port = Port(
    type="file_selector",
    name="infile",
    label="Select File",
    controls=[file_selector_control],
)
file_selector_node = Node(
    type="file_selector",
    label="File Selector",
    method=file_selector,
    inputs=[file_selector_port],
    outputs=[file_selector_port],
)

fconfig = Config.from_function_list(
    all_functions, 
    extra_nodes=[file_selector_node], 
    extra_ports=[file_selector_port]
)           
`

Generates error in browser: Cannot read properties of undefined (reading 'length')

**Comment by idling-mind** [comment]
There was a bug which is fixed now. Give it a try.
