### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maxfrei750** [idling-mind/flowfunc#23]
Really awesome work! Thank you!

I saw that you don't provide a license (yet). Are there plans to add one? Otherwise, it might be problematic for some folks (like me :sweat_smile: ) to use your package.

**Comment by idling-mind** [comment]
@maxfrei750 Thanks for noticing. Fixed now.

**Comment by maxfrei750** [comment]
@idling-mind Thanks for the quick fix! :+1:
