### ISSUE TITLE
pydantic version is incompatible with some existing packages (thinc and spacy)

### ISSUE THREAD

**Issue by bloomv** [idling-mind/flowfunc#5]
flowfunc requires pydantic>=1.9 ( pydantic-1.10.2 installed) is incompatible with existing packages of my app:
- thinc 8.0.15 requires pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4, but you have pydantic 1.10.2 which is incompatible.
- spacy 3.2.4 requires pydantic!=1.8,!=1.8.1,<1.9.0,>=1.7.4, but you have pydantic 1.10.2 which is incompatible.

I have to solve these dependency conflicts.

After all, I have successfully installed flowfunc-0.0.1 and pydantic-1.10.2.  

 Next, run the basic usage example.

**Comment by idling-mind** [comment]
I believe flowfunc should work with previous versions of pydantic as well. I'd suggest you override the pydantic version and try with spacy and thinc and see if it works for you.
