### ISSUE TITLE
Fix basic usage example bugs

### ISSUE THREAD

**Issue by bloomv** [idling-mind/flowfunc#6]
My development environment is:

- Windows 10
- python 3.7.9
- dash 2.0

When I run the basic usage example from [https://github.com/idling-mind/flowfunc#readme](url):

C:\Users\chenxiaowang\dash-apps\flowfunc-master\learn>ppython basic_usage.py
Traceback (most recent call last):
  File "basic_usage.py", line 5, in <module>
    from flowfunc.config import Config
  File "C:\Panda3D-1.10.10-x64\python\lib\site-packages\flowfunc\config.py", line 5, in <module>
    from typing import Any, Callable, List, Optional, Union, get_args, get_origin
ImportError: cannot import name 'get_args' from 'typing' (C:\Panda3D-1.10.10-x64\python\lib\typing.py)

I fixed it:

- pip install typing_extensions
- modify flowfunc\config.py

Modify flowfunc\config.py as the flowing:

- delete one line:

`from typing import Any, Callable, List, Optional, Union, get_args, get_origin`

- add these lines:

```
from typing import Any, Callable, List, Optional, Union
try:
    from typing import  get_args
except ImportError:
    from typing_extensions import  get_args
try:
    from typing import  get_args
except ImportError:
    from typing_extensions import  get_args
```

I aslo modify basic uasage exmaple code:
```
@app.callback(
    Output("output", "children"),
    Input("btn_run", "n_clicks"),
    State("nodeeditor", "nodes"),
    #prevent_initial_callbacks=False
)
def run_nodes(nclicks: int, output_nodes: Dict[str, OutNode]):
    """Run the node layout"""
    # The result is a dictionary of OutNode objects
    # check output_nodes is None 
    if output_nodes is None:
        return []
    result = runner.run(output_nodes)
    output = []
    for node in result.values():
        # node.result contains the result of the node
        output.append(
            html.Div([html.H1(f"{node.type}: {node.id}"), html.P(str(node.result))])
        )
    return output

if __name__ == "__main__":
    # AttributeError: 'Dash' object has no attribute 'run'
    ##app.run() 
   app.run_server(debug = True, host = '192.168.0.114', use_reloader=False, dev_tools_hot_reload=False)
```

The basic usage example has run successfully on my development environment. VERY COOL!

**Comment by idling-mind** [comment]
@bloomv Good to know it worked for you. Do you think you can create a pull request with the changes?
