### ISSUE TITLE
Can not input float data type

### ISSUE THREAD

**Issue by bloomv** [idling-mind/flowfunc#7]
Define a function:

```
def add_int_float(
    a: int, b: float
) -> float:
    return a + b
```
and run:
```
methods_dao.add_int_float: None
1 validation error for AddIntFloat b field required (type=value_error.missing)
```
None Control component  provided for input b with data type **float**.

**Comment by idling-mind** [comment]
I tested it on the basic example and seems to work fine. Did you leave the field blank? This is a pydantic validation error when you haven't provided a value to a field.

Can you share your full run script?

PS: I have noticed that the front end shows a red border around the text box when you enter a float value. This is something I have to figure out how to resolve from the front end framework, [flume](https://github.com/chrisjpatty/flume).
